networks:
  exchbook_net:
    driver: bridge

services:
  database:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ugzQyMRkAOcqeWYWCOIeeDvCRzyYwwda
      - POSTGRES_DB=exchbook_db
    volumes:
      - ./src/main/resources/init-db.sql:/docker-entrypoint-initdb.d/intit-db.sql
    ports:
      - "5432:5432"
    networks:
      - exchbook_net

