networks:
  exchbook_net:
    driver: bridge

services:
  database:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ugzQyMRkAOcqeWYWCOIeeDvCRzyYwwda
      - POSTGRES_DB=exchbook_db
      #volumes:
      #- postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U finanManag -d financial_db" ]
      interval: 8s
      timeout: 3s
      retries: 2
    networks:
      - exchbook_net

